### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SIGTTOU'

### ISSUE THREAD

**Issue by tnkteja** [tartley/rerun#12]
Traceback (most recent call last):
  File "C:\Python27\Scripts\rerun-script.py", line 9, in <module>
    load_entry_point('rerun==1.0.26', 'console_scripts', 'rerun')()
  File "c:\python27\lib\site-packages\rerun\rerun.py", line 146, in main
    signal.signal(signal.SIGTTOU, signal.SIG_IGN)
AttributeError: 'module' object has no attribute 'SIGTTOU'

**Comment by jmobley0429** [comment]
I was able to correct this on my end (Windows 10) by changing the that line from:

`signal.signal(signal.SIGTTOU, signal.sig_IGN)`

to

`signal.signal(signal.SIGTERM, signal.sig_IGN)`
